# @hostname = xylenet.online
# @hostname = https://3c6e-45-248-56-22.ngrok-free.app/api
# # @hostname = 997d-2405-201-800d-8c86-e562-d727-7055-d46f.ngrok-free.app

# @protocal = https
# @endpoint = {{protocal}}://{{hostname}}/api
# @endpoint = http://localhost/api
@endpoint =https://f853-103-142-115-55.ngrok-free.app/api


###
GET {{endpoint}}/visa-dpt/mofa-entry-list
?status=sjgfs





##################################################################

######################      Visa DPT         ######################

##################################################################


# ================      Mol Work Permit      =============== #

### Fetch List
GET {{endpoint}}/visa-dpt/mol-work-permit-cancel-list


### post 
Post  {{endpoint}}/visa-dpt/mol-work-permit-cancel
content-type: application/json


{
    "candidate_id" : 23,
    "client_invoice" : "yes",
    "penalty_amount" : 456,
    "mistake_by" : "AGENT/CANDIDATE"
}




# ================      Account Candidate List      =============== #

### Fetch List
GET {{endpoint}}/account/account-candidate-list


### Post 
Post  {{endpoint}}/account/account-candidate
content-type: application/json


{
    "candidate_id" : 23,
    "client_invoice" : "yes",
    "penalty_amount" : 456,
    "mistake_by" : "AGENT/CANDIDATE"
}




# ================      Account Dashboard      =============== #

### Fetch List
GET {{endpoint}}/account/account-dashboard-list


### Post 
Post  {{endpoint}}/account/account-dashboard
content-type: application/json


{
    "candidate_id" : 23,
    "client_invoice" : "yes",
    "penalty_amount" : 456,
    "mistake_by" : "AGENT/CANDIDATE"
}







# ######################
//  ------------   Receive Payment   ------------ \\


# ================      Receive Payment      =============== #

### Fetch Candidate List
# for index page
GET {{endpoint}}/account/receive-payment-candidate-list

### Fetch Payment List
GET {{endpoint}}/account/receive-payment-candidate-list?candidate_id=2



# /account/receive-payment/{id} id = payment id from Payment List
### Patch 
Patch  {{endpoint}}/account/receive-payment/4
content-type: application/json

{
    "amount" : 0
}

### Delete
Delete  {{endpoint}}/account/receive-payment/4













##################################################################

######################      Account         ######################

##################################################################


# ================      Account Dashboard      =============== #

### Fetch Account Dashboard List
GET {{endpoint}}/account/account-dashboard-list


### Patch Account Dashboard
POST  {{endpoint}}/account/account-dashboard-cancel/3
content-type: application/json


{
    "client_invoice" : "NO",
    "penalty_amount" : 456,
    "mistake_by" : "AGENT/CANDIDATE"
}

# mistake_by => AGENT/CANDIDATE, SOUNDLINES, CLIENT




# ================      Candidate Discount      =============== #

### Fetch Candidate Discount List
GET {{endpoint}}/account/candidate-discount-list


### Add Candidate Discount List
POST  {{endpoint}}/account/candidate-discount-list
content-type: application/json

{
    "selection_list":[
        {
            "id": 2,
            "discount": 60,
            "discount_type": "NORMAL DISCOUNT",
            "discount_remarks": "h dvd"
        },
        {
            "id": 4,
            "discount": 90,
            "discount_type": "ERROR DISCOUNT",
            "discount_remarks": "h dvd"
        }
    ]
}

# discount_type => NORMAL DISCOUNT, ERROR DISCOUNT





# ================      Candidate Discount Approve      =============== #

### Fetch Candidate Discount Approve List
GET {{endpoint}}/account/candidate-discount-approve-list


### Patch Candidate Discount Approve List
PATCH  {{endpoint}}/account/candidate-discount-approve-list
content-type: application/json


{
    "selection_list":[
        {
            "discount_id": 2,
            "status": 1
        },
        {
            "discount_id": 4,
            "status": 1
        }
    ]
}

# status => 1 for approve , 2 for reject








# ================      Reject Cancel Approve      =============== #

### Fetch Reject Cancel Approve List
GET {{endpoint}}/account/reject-cancel-approve-list

### Update Reject Cancel Approve List
PATCH {{endpoint}}/account/reject-cancel-approve-list
content-type: application/json

{
    "selection_list":[
        {
            "id":3,
            "mofa_cancel_id":1,
            "status":1
        }
    ]
}






# ================      Agent Payment      =============== #

### Fetch Agent Payment List
GET {{endpoint}}/account/agent-payment-list
?agent_id=3


### Add Agent Payment
POST   {{endpoint}}/account/agent-payment/agent-add
content-type: application/json

{
    "agent_id":12,
    "amount":1200,
    "description":"dfjgdfjgdfjg"
}


### Add Candidate Payment
POST   {{endpoint}}/account/agent-payment/candidate-add
content-type: application/json

{
    "candidate_id":3,
    "agent_id":12,
    "amount":1200,
    "remarks":"amio"
}


### Add Agent Payment List
POST   {{endpoint}}/account/agent-payment-list
content-type: application/json

{
    "selection_list":[
        {
            "id":3,
            "amount":34,
            "bulk_payment_id":1,
            "advance":0,
            "payment_date":""
        }
    ]
}




### Fetch Agent Payment Receive Payment List
GET {{endpoint}}/account/agent-payment/receive-payment-list
?candidate_id=2

# onclick bulk payment used amount bulk_payment_id
# onclick candiadte recieve payment candidate_id











# ================      Direct Payment      =============== #

### Fetch Direct Payment List
GET {{endpoint}}/account/direct-payment-list?agent_id=3


### Add Advance Payment
POST   {{endpoint}}/account/direct-payment/advance-payment-add
content-type: application/json

{
    "name":"amio",
    "amount":1289,
    "passport_no":"gsfuwef5u",
    "received_date":"02/05/2023",
    "remarks":"remarks"
}


### Read Advance Payment List
GET {{endpoint}}/account/direct-payment/advance-payment-list

### Add Candidate Payment
POST {{endpoint}}/account/direct-payment/candidate-add
content-type: application/json

{
    "candidate_id":1,
    "agent_id":12,
    "amount":1200,
    "remarks":"amio"
}


### Add Agent Payment List
POST   {{endpoint}}/account/direct-payment-list
content-type: application/json

{
    "selection_list":[
        {
            "id":3,
            "amount":34,
            "bulk_payment_id":1,
            "advance":0,
            "payment_date":""
        }
    ]
}




### Fetch Agent Payment Receive Payment List
GET {{endpoint}}/account/agent-payment/receive-payment-list
?bulk_payment_id=0&candidate_id=2

# onclick bulk payment used amount bulk_payment_id
# onclick candiadte recieve payment candidate_id











# ================      Agent Commission Add      =============== #

### Read Advance Payment List
GET {{endpoint}}/account/agent-commission-add?passport_no
#N4948559


### Add Candidate Payment
PATCH {{endpoint}}/account/agent-commission-add/3
content-type: application/json

{
    "agent_commission":3
}











# ================      Agent Commissions      =============== #

### Read Agent Commission List
GET {{endpoint}}/account/agent-commission-list



### Add Cash Payment
POST {{endpoint}}/account/agent-commission/cash-payment
content-type: application/json

{
    "name":"amio",
    "passport_no":"jhb2r23ryiu",
    "agent_id":12,
    "amount":1200,
    "remarks":"amio"
}



### Add Candidate Payment
POST {{endpoint}}/account/agent-commission/bulk-payment
content-type: application/json

{
    "name":"amio",
    "passport_no":"jhb2r23ryiu",
    "agent_id":12,
    "amount":1200,
    "remarks":"amio"
}



### Fetch Agent Payment Receive Payment List
GET {{endpoint}}/account/agent-commission/receive-payment-list
?bulk_payment_id=0&candidate_id=1

# onclick bulk payment used amount bulk_payment_id
# onclick candiadte recieve payment candidate_id












# ================      Penalty After Deployment      =============== #
#2 done 1 pending remark
### Read Penalty After Deployment List
#done
GET {{endpoint}}/account/penalty-after-deployment-list?status=no

# status=no for add
# status=yes for edit


### Add Penalty After Deployment
#done
POST {{endpoint}}/account/penalty-after-deployment-list
content-type: application/json

{
    "selection_list":[
        {
            "id": 5,
            "penalty_after_departure": 23,
            "penalty_remarks": "something"
        }
    ]
}



### Update Penalty After Deployment
# where this function is needed?
PATCH {{endpoint}}/account/penalty-after-deployment-list
content-type: application/json

{
    "selection_list":[
        {
            "id": 5,
            "penalty_after_departure": 230,
            "penalty_remarks": "something"
        }
    ]
}











# ================      Agent Bulk Payment      =============== #

### Read Agent Bulk Payment List
GET {{endpoint}}/account/agent-bulk-payment-list



### Add Agent Bulk Payment
POST {{endpoint}}/account/agent-bulk-payment
content-type: application/json

{
    "agent_id":12,
    "amount":1200,
    "description":"amio"
}



### Update Agent Bulk Payment
PATCH {{endpoint}}/account/agent-bulk-payment/5
content-type: application/json

{
    "agent_id":12,
    "amount":1200,
    "description":"new description"
}



### Delete Agent Bulk Payment
DELETE {{endpoint}}/account/agent-bulk-payment/5










# ================      Incentives      =============== #

### Read Incentives List
GET {{endpoint}}/account/incentive-list?status=no

# status=no for add
# status=yes for edit



### Add Incentives
POST {{endpoint}}/account/incentive-list
content-type: application/json

{
    "job_order_list":[
        {
            "id": 10,
            "manager_incentive": 23,
            "staff_incentive": 54
        }
    ]
}



### Update Incentives
PATCH {{endpoint}}/account/incentive-list
content-type: application/json

{
    "job_order_list":[
        {
            "id": 10,
            "manager_incentive": 0,
            "staff_incentive": 60
        }
    ]
}



# ================      Delhi Agent Payment      =============== #

### Read Delhi Agent Payment List
GET {{endpoint}}/account/delhi-agent-payment-list



### Add In Account
POST {{endpoint}}/account/delhi-agent-payment/add-in-account
content-type: application/json

{
    "id": 2,
    "is_without": 0,
    "agent_id": 2,
    "amount": 23,
    "description": "description"
}



### Update Delhi Agent Payment
PATCH {{endpoint}}/account/delhi-agent-payment/2
content-type: application/json

{
    "is_without": 0,
    "dad_amount": 44
}






# ================      Account Candidate List      =============== #

### Read Account Candidate List
# GET {{endpoint}}/account/account-candidate-list

GET {{endpoint}}/account/service-charge-list



### Update Account Candidate List
PATCH {{endpoint}}/account/service-charge-list
content-type: application/json

{
    "is_without": 0,
    "visa_cancel_penalty": 45,
    "visa_cancel_remarks": "gvfgds"
}


























##################################################################

######################      Invoice         ######################

##################################################################


# ================      Client Suspend Amount      =============== #

### Read Client Suspend Amount List
GET {{endpoint}}/invoice-dpt/client-suspend-amount-list



### Add Client Suspend Amount
POST {{endpoint}}/invoice-dpt/client-suspend-amount
content-type: application/json

{
    "company_id":3,
    "payment_received_date":"54/343/343",
    "amount_received":3,
    "payment_description":"hdfvdfh"
}


### Get Client Suspend Amount
GET {{endpoint}}/invoice-dpt/client-suspend-amount/1


### Update Client Suspend Amount
PATCH {{endpoint}}/invoice-dpt/client-suspend-amount/3
content-type: application/json

{
    "company_id":3,
    "payment_received_date":"54",
    "amount_received":3,
    "payment_description":"hdfvdfh"
}


### Delete Client Suspend Amount
DELETE {{endpoint}}/invoice-dpt/client-suspend-amount/3


###
GET {{endpoint}}/invoice-dpt/client-suspend-amount/adjust-amount-list
?company_id=3






# ================      Client Additional Invoice      =============== #

### Read Client Additional Invoice List
GET {{endpoint}}/invoice-dpt/client-additional-invoice-list



### Add Client Additional Invoice
POST {{endpoint}}/invoice-dpt/client-additional-invoice
content-type: application/json

{
    "company_id":3,
    "invoice_date":"24-9-23",
    "invoice_number":"erw",
    "invoice_amount":23
}


### Get Client Additional Invoice
GET {{endpoint}}/invoice-dpt/client-additional-invoice/1


### Update Client Additional Invoice
PATCH {{endpoint}}/invoice-dpt/client-additional-invoice/3
content-type: application/json

{
    "company_id":3,
    "invoice_date":"8-4-23",
    "invoice_number":"vbfdkvbdfhb",
    "invoice_amount":33
}


### Delete Client Additional Invoice
DELETE {{endpoint}}/invoice-dpt/client-additional-invoice/3







# ================      Candidate Ticket Charge      =============== #

### Read Candidate Ticket Charge List
GET {{endpoint}}/invoice-dpt/candidates-ticket-charge-list



### Add Candidate Ticket Charge
POST {{endpoint}}/invoice-dpt/candidates-ticket-charge-list
content-type: application/json

{
    "selection_list":[
        {
            "id":2,
            "is_without":0,
            "ticket_charges":45,
            "ticket_charge_currency":"IND"
        },
        {
            "id":6,
            "is_without":1,
            "ticket_charges":24,
            "ticket_charge_currency":"USD"
        }
    ]
}







# ================      Candidate Invoice Raise      =============== #

### Read Candidate Invoice Raise List
GET {{endpoint}}/invoice-dpt/candidates-invoice-raise-list



### Add Candidate Invoice Raise
POST {{endpoint}}/invoice-dpt/candidates-invoice-raise-list
content-type: application/json

{
    "selection_list":[
        {
            "id":2,
            "is_without":0,
            "total_charges":32,
            "invoice_number":"jhfvhjdsfbvksd",
            "invoice_date":"4-5-67",
            "bank_id":1
        },
        {
            "id":6,
            "is_without":1,
            "total_charges":25,
            "invoice_number":"jhfvhjdsfbvksd",
            "invoice_date":"4-5-12",
            "bank_id":7
        }
    ]
}


### Update Candidate Invoice Raise
PATCH {{endpoint}}/invoice-dpt/candidates-invoice-raise/1
content-type: application/json

{
    "is_without":0,
    "total_charges":2,
    "invoice_number":"jhfvhjdsfbvksd",
    "invoice_date":"4-5-67",
    "bank_id":1
}



### Update Candidate Invoice Raise
DELETE {{endpoint}}/invoice-dpt/candidates-invoice-raise/3
content-type: application/json

{
    "is_without":1
}







# ================      Candidate Invoice Charge      =============== #

### Read Candidate Invoice Charge List
GET {{endpoint}}/invoice-dpt/candidates-invoice-charge-list



### Add Candidate Invoice Charge
POST {{endpoint}}/invoice-dpt/candidates-invoice-charge-list
content-type: application/json

{
    "selection_list":[
        {
            "id":2,
            "is_without":0,
            "other_charges":28,
            "other_charge_currency":"USD",
            "service_charges":4,
            "service_charge_currency":"USD",
            "ticket_charges":36,
            "ticket_charge_currency":"IND",
            "total_charges":58
        },
        {
            "id":6,
            "is_without":1,
            "other_charges":24,
            "other_charge_currency":"IND",
            "service_charges":24,
            "service_charge_currency":"USD",
            "ticket_charges":24,
            "ticket_charge_currency":"IND",
            "total_charges":45
        }
    ]
}







# ================      Candidate Invoice Number      =============== #

### Read Candidate Invoice Number List
GET {{endpoint}}/invoice-dpt/candidates-invoice-number-list



### Add Candidate Invoice Number
POST {{endpoint}}/invoice-dpt/candidates-invoice-number-list
content-type: application/json

{
    "selection_list":[
        {
            "id":2,
            "is_without":0,
            "invoice_number":"jhdftg",
            "invoice_date":"17-5-15",
            "bank_id":7
        },
        {
            "id":6,
            "is_without":1,
            "invoice_number":"tdcag",
            "invoice_date":"23-1-23",
            "bank_id":4
        }
    ]
}








# ================      Client Payment      =============== #

### Read Client Payment List
GET {{endpoint}}/invoice-dpt/client-payment-list



### Add Client Payment
POST {{endpoint}}/invoice-dpt/client-payment
content-type: application/json

{
    "company_id":2,
    "invoice_number":"abc",
    "invoice_date":"4-5-23",
    "amount":24,
    "date":"4-7-23",
    "description":"add payment"
}

# client_suspend_amount_id  optional 
# use if adjust from suspend amount



### Update Client Payment
PATCH {{endpoint}}/invoice-dpt/client-payment/1
content-type: application/json

{
    "amount":4,
    "date":"4-7-23",
    "description":"add payment"
}



### Update Client Payment List
PATCH {{endpoint}}/invoice-dpt/client-payment-list
content-type: application/json

{
    "payment_list":[
        {
            "id":1,
            "amount":47,
            "date":"6-11-22",
            "description":"update payment 1"
        },
        {
            "id":6,
            "amount":52,
            "date":"8-2-23",
            "description":"update payment 2"
        }
    ]
}



### Remove Update Client Payment
DELETE {{endpoint}}/invoice-dpt/client-payment/1


# Extended APi
### Read Client Payment Candidate List By Invoice Number
GET {{endpoint}}/invoice-dpt/client-payment/candidate-list
?invoice_number=abc


### Read Client Payment List
GET {{endpoint}}/invoice-dpt/client-payment/payment-list
?invoice_number=abc





# ================      Client Additional Payment      =============== #

### Read Client Additional Payment List
GET {{endpoint}}/invoice-dpt/client-additional-payment-list



### Add Client Additional Payment
POST {{endpoint}}/invoice-dpt/client-additional-payment
content-type: application/json

{
    "company_id":2,
    "invoice_number":"abc",
    "invoice_date":"4-5-23",
    "amount":24,
    "date":"4-7-23",
    "description":"add payment"
}

# client_suspend_amount_id  optional 
# use if adjust from suspend amount



### Update Client Additional Payment
PATCH {{endpoint}}/invoice-dpt/client-additional-payment/1
content-type: application/json

{
    "amount":4,
    "date":"4-7-23",
    "description":"add payment"
}



### Update Client Additional Payment List
PATCH {{endpoint}}/invoice-dpt/client-additional-payment-list
content-type: application/json

{
    "payment_list":[
        {
            "id":1,
            "amount":47,
            "date":"6-11-22",
            "description":"update payment 1"
        },
        {
            "id":6,
            "amount":52,
            "date":"8-2-23",
            "description":"update payment 2"
        }
    ]
}



### Remove Update Client Additional Payment
DELETE {{endpoint}}/invoice-dpt/client-additional-payment/1


# Extended APi

### Read Client Additional Payment List
GET {{endpoint}}/invoice-dpt/client-additional-payment/payment-list
?invoice_number=abc





# ================      Invoice Courier Date      =============== #

### Read Invoice Courier Date List
GET {{endpoint}}/invoice-dpt/invoice-courier-date-list



### Add Invoice Courier Date
POST {{endpoint}}/invoice-dpt/invoice-courier-date-list
content-type: application/json

{
    "invoice_list":[
        {
            "company_name": "CA",
            "invoice_number": "jdsgfs56f",
            "invoice_date": "16-07-23",
            "invoice_type": "Normal",
            "total_charges": 12,
            "invoice_sector": "sector a",
            "courier_date": "23-07-23"
        },
        {
            "company_name": "CB",
            "invoice_number": "hgfr",
            "invoice_date": "17-07-23",
            "invoice_type": "Additional",
            "total_charges": 52,
            "invoice_sector": "sector g",
            "courier_date": "23-07-23"
        }
    ]
}





# ================      Invoice Dispatched      =============== #

### Read Invoice Dispatched List
GET {{endpoint}}/invoice-dpt/invoice-dispatched-list



### Add Invoice Dispatched
POST {{endpoint}}/invoice-dpt/invoice-dispatched-list
content-type: application/json

{
    "invoice_list":[
        {
            "id": 4,
            "received": "No",
            "received_date": ""
        },
        {
            "id": 3,
            "received": "Yes",
            "received_date": "16-07-23"
        }
    ]
}





# ================      Invoice Admin Remarks      =============== #

### Read Invoice Admin Remarks List
GET {{endpoint}}/invoice-dpt/invoice-admin-remarks-list



### Add Invoice Admin Remarks
POST {{endpoint}}/invoice-dpt/invoice-admin-remarks-list
content-type: application/json

{
    "invoice_list":[
        {
            "id": 3,
            "given_to": "Aka 1",
            "given_to_date": "23-07-23",
            "given_to_remarks": "NA"
        }
    ]
}




### Read Invoice Contact Person List
GET {{endpoint}}/invoice-dpt/invoice-contact-person-list



### Add Invoice Contact Person
POST {{endpoint}}/invoice-dpt/invoice-contact-person-list
content-type: application/json

{
    "invoice_list":[
        {
            "id": 1,
            "contact_person_name": "Aka 1",
            "contact_person_remarks": "NA"
        }
    ]
}



### Read Invoice Submit List
GET {{endpoint}}/invoice-dpt/invoice-submit-list



### Add Invoice Submit
POST {{endpoint}}/invoice-dpt/invoice-submit/3
content-type: multipart/form-data

{
    "submit_file": "SELECT A File",
    "submit_remarks": "NA",
    "status": "Yes"
}














##################################################################

######################      Immigration         ######################

##################################################################


# ================      Immigration Dashboard      =============== #

### Read Immigration Dashboard List
GET {{endpoint}}/immigration-dpt/immigration-dashboard-list



### Add Immigration Dashboard
POST {{endpoint}}/immigration-dpt/immigration-dashboard-list
content-type: application/json

{
    "selection_list":[
        {
            "id":2,
            "is_without":0,
            "immigration_required":"Yes",
            "immigration_submission_date":"6-11-22",
            "immigration_received_date":"6-11-22"
        },
        {
            "id":6,
            "is_without":1,
            "immigration_required":"No",
            "immigration_submission_date":"6-11-22",
            "immigration_received_date":"6-11-22"
        }
    ]
}

# immigration_required => Yes/No


### Update Immigration Dashboard reject remarks
PATCH {{endpoint}}/immigration-dpt/immigration-dashboard/2
content-type: application/json

{
    "is_without": 0,
    "immigration_reject_remarks": "fdgesfe"
}









 

# ================      Immigration Done PP Release      =============== #

### Read Immigration Done PP Release List
GET {{endpoint}}/immigration-dpt/immigration-done-pp-release-list
?status=yes
# default status=no 

# status=no for add 
# status=yes for edit


### Add Immigration Done PP Release
POST {{endpoint}}/immigration-dpt/immigration-done-pp-release-list
content-type: application/json

{
    "selection_list":[
        {
            "id":2,
            "is_without":0,
            "given_to":"Given To Delhi Office",
            "given_date":"6-11-22"
        },
        {
            "id":6,
            "is_without":1,
            "given_to":"Given To Cancelation",
            "given_date":"6-11-22"
        }
    ]
}

# immigration_required => Yes/No
# Given To RC
# Given To Agent
# Given To Candidate
# Given To Accounts
# Given To Cancelation
# Given To Delhi Office
# Given To Hyderabad Office
# Given for Amendment
# Given for Bio-Matric
# Given To Others


### Update Immigration Done PP Release reject remarks
PATCH {{endpoint}}/immigration-dpt/immigration-done-pp-release/2
content-type: application/json

{
    "is_without": 0,
    "given_to": "Given To Delhi Office",
    "given_date": "9-11-23"
}











# ================      Index For Ewakala      =============== #

### Read Index For Ewakala List
GET {{endpoint}}/immigration-dpt/index-for-ewakala-list

### Read Index For Ewakala List
GET {{endpoint}}/ticketing-dpt/tickets-dashboard/ticket-to-be-booked-list












##################################################################################

######################      Delhi Account Dashboard         ######################

##################################################################################


# ================      Candidate List     =============== #

### Read Candidate List
GET {{endpoint}}/delhi-account-dasboard/candidate-list


### Add Candidate
POST {{endpoint}}/delhi-account-dasboard/candidate-list
content-type: application/json

{
    "selection_list":[
        {
            "id":2,
            "is_without":0,
            "dad_service_tax": "Yes",
            "dad_amount": 109
        },
        {
            "id":6,
            "is_without":1,
            "dad_service_tax": "No",
            "dad_amount": 90
        }
    ]
}

# dad_service_tax => Yes/No
# optional parameter => given_to and given_date





# ================      RC Candidates List      =============== #

### Read RC Candidates List List
GET {{endpoint}}/delhi-account-dasboard/rc-candidate-list
?status=yes
# default status=no 

# status=no for add 
# status=yes for edit


### Add RC Candidates List
PATCH {{endpoint}}/delhi-account-dasboard/rc-candidate-list
content-type: application/json

{
    "selection_list":[
        {
            "id":2,
            "is_without":0,
            "dad_pp_received": 1,
            "dad_pp_received_date": "6-11-22"
        },
        {
            "id":6,
            "is_without":1,
            "dad_pp_received": 0,
            "dad_pp_received_date": "6-09-22"
        }
    ]
}










# ================      RC PP Received      =============== #

### Read RC PP Received List
POST    {{endpoint}}/visa-dpt/mol-work-permit-cancel
content-type: application/json

{
    "candidate_id" : 23,
    "client_invoice" : "yes",
    "penalty_amount" : 456,
    "mistake_by" : "AGENT/CANDIDATE"
}





# ########################################################################################################### #
# ########################################################################################################### #
# ########################################################################################################### #
# ########################################################################################################### #

ticketing-dpt/rm-advance-booking-list?immigration_status={value}
yes=ECR
no=ECNR
pending=PENDING

# ###############  tiketing dashboard ############### #

# index page api
ticketing-dpt/tickets-dashboard-list



# request parameters
setting_visa
job_order_no
company_name
candidate_name
passport_no
actual_profession
mofa_number
agent_name
rc_name
visa_received_date
visa_expire_date
ticketing_sector_from
ticketing_sector_to
required_date
priority
air_ticket
visa_authorisation
division
# editable
ticketing_under_process
ticketing_trying

get ticketing-dpt/tickets-dashboard/ticket-to-be-booked-list
post ticketing-dpt/tickets-dashboard/ticket-to-be-booked-list






# ################  ################ #
# request parameters
setting_visa
job_order_no
company_name
candidate_name
passport_no
actual_profession
mofa_number
agent_name
rc_name
visa_received_date
visa_expire_date
ticketing_sector_from
ticketing_sector_to
required_date
priority
air_ticket
required_date
priority
visa_no
visa_date
pp_expiry_date
visa_issued_date

# editable
air_line
ticket_issue_date
ticketing_pnr_no
ticketing_departure_date
agency
amount

get ticketing-dpt/tickets-dashboard/ticket-under-process-list
post ticketing-dpt/tickets-dashboard/ticket-under-process-list
delete ticketing-dpt/tickets-dashboard/ticket-under-process/{id}






# ############## ticket trying ############## #
# request parameters
setting_visa
job_order_no
company_name
candidate_name
passport_no
actual_profession
mofa_number
agent_name
rc_name
visa_received_date
visa_expire_date
ticketing_sector_from
ticketing_sector_to
required_date
priority
air_ticket
required_date
priority
air_line
visa_no
visa_date
pp_expiry_date
visa_issued_date

# editable
air_line
ticket_issue_date
ticketing_pnr_no
ticketing_departure_date
agency
amount

get ticketing-dpt/tickets-dashboard/ticket-trying-list
post ticketing-dpt/tickets-dashboard/ticket-trying-list
delete ticketing-dpt/tickets-dashboard/ticket-trying/{id}







# ################   agency invoice awaiting  ################ #
# request parameters
setting_visa
job_order_no
company_name
candidate_name
passport_no
actual_profession
mofa_number
agent_name
rc_name
visa_received_date
visa_expire_date
ticketing_sector_from
ticketing_sector_to
required_date
priority
air_ticket
ticketing_pnr_no
ticketing_departure_date
ticket_issue_date
agency
amount
required_date
priority
air_ticket
air_line
visa_no
visa_date
pp_expiry_date
visa_issued_date

# editable
ticketing_invoice_no
ticketing_invoice_date

get ticketing-dpt/tickets-dashboard/agency-invoice-awaiting-list
post ticketing-dpt/tickets-dashboard/agency-invoice-awaiting-list
post ticketing-dpt/tickets-dashboard/agency-invoice-awaiting-list
